# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
txt="Hi there sam!"
x=txt.split()
print(x)

['Hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet="Earth"
diameter="12742"
print('The diameter of{} is {} kilometer.'.format(planet,diameter));

The diameter ofEarth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [4]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array = np.zeros(10)
print("Array of 10 zeros:")
print(array)

Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
array = np.ones(10)*5
print("Array of 10 fives:")
print(array)

Array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
x = np.arange(0 , 9).reshape(3,3)
print (x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [9]:
import numpy as np
array1 = np.array([[1,2,3]])
array2= np.array([[4,5,6]])
x= np.concatenate((array1 , array2),axis = None)
print(x)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [10]:
import pandas as pd
lst = [[1,'arya stark',20],[2, 'Jon snow' , 32],[3,'leone' ,25]]
df = pd.DataFrame(lst,columns =['S.N0' , 'name', 'age'])
print(df)

   S.N0        name  age
0     1  arya stark   20
1     2    Jon snow   32
2     3       leone   25


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [11]:
import datetime
import pandas as pd
 
test_date = datetime.datetime.strptime("01-1-2022", "%d-%m-%Y")
 

K = 41
 
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2022', '02-01-2022', '03-01-2022', '04-01-2022', '05-01-2022',
       '06-01-2022', '07-01-2022', '08-01-2022', '09-01-2022', '10-01-2022',
       '11-01-2022', '12-01-2022', '13-01-2022', '14-01-2022', '15-01-2022',
       '16-01-2022', '17-01-2022', '18-01-2022', '19-01-2022', '20-01-2022',
       '21-01-2022', '22-01-2022', '23-01-2022', '24-01-2022', '25-01-2022',
       '26-01-2022', '27-01-2022', '28-01-2022', '29-01-2022', '30-01-2022',
       '31-01-2022', '01-02-2022', '02-02-2022', '03-02-2022', '04-02-2022',
       '05-02-2022', '06-02-2022', '07-02-2022', '08-02-2022', '09-02-2022',
       '10-02-2022'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [12]:
import pandas as pd
lst = [[1,'aaa',22],[2, 'bbb' , 24]]
df = pd.DataFrame(lst,columns =['S.N0' , 'name', 'age'])
print(df)

   S.N0 name  age
0     1  aaa   22
1     2  bbb   24
